export const currencies = [
  { name: "Nigerian Naira (NGN)", currency: "NGN", symbol: "₦", flag: "https://flagcdn.com/ng.svg" },
  { name: "US Dollar (USD)", currency: "USD", symbol: "$", flag: "https://flagcdn.com/us.svg" },
  { name: "Pound Sterling (GBP)", currency: "GBP", symbol: "£", flag: "https://flagcdn.com/gb.svg" },
  { name: "UAE Dirham (AED)", currency: "AED", symbol: "د.إ", flag: "https://flagcdn.com/ae.svg" },
  { name: "Afghan Afghani (AFN)", currency: "AFN", symbol: "؋", flag: "https://flagcdn.com/af.svg" },
  { name: "Albanian Lek (ALL)", currency: "ALL", symbol: "L", flag: "https://flagcdn.com/al.svg" },
  { name: "Armenian Dram (AMD)", currency: "AMD", symbol: "֏", flag: "https://flagcdn.com/am.svg" },
  { name: "Netherlands Antillean Guilder (ANG)", currency: "ANG", symbol: "ƒ", flag: "https://flagcdn.com/an.svg" },
  { name: "Angolan Kwanza (AOA)", currency: "AOA", symbol: "Kz", flag: "https://flagcdn.com/ao.svg" },
  { name: "Argentine Peso (ARS)", currency: "ARS", symbol: "$", flag: "https://flagcdn.com/ar.svg" },
  { name: "Australian Dollar (AUD)", currency: "AUD", symbol: "$", flag: "https://flagcdn.com/au.svg" },
  { name: "Aruban Florin (AWG)", currency: "AWG", symbol: "ƒ", flag: "https://flagcdn.com/aw.svg" },
  { name: "Azerbaijani Manat (AZN)", currency: "AZN", symbol: "₼", flag: "https://flagcdn.com/az.svg" },
  { name: "Bosnia-Herzegovina Convertible Mark (BAM)", currency: "BAM", symbol: "KM", flag: "https://flagcdn.com/ba.svg" },
  { name: "Barbados Dollar (BBD)", currency: "BBD", symbol: "$", flag: "https://flagcdn.com/bb.svg" },
  { name: "Bangladeshi Taka (BDT)", currency: "BDT", symbol: "৳", flag: "https://flagcdn.com/bd.svg" },
  { name: "Bulgarian Lev (BGN)", currency: "BGN", symbol: "лв", flag: "https://flagcdn.com/bg.svg" },
  { name: "Bahraini Dinar (BHD)", currency: "BHD", symbol: "ب.د", flag: "https://flagcdn.com/bh.svg" },
  { name: "Burundian Franc (BIF)", currency: "BIF", symbol: "FBu", flag: "https://flagcdn.com/bi.svg" },
  { name: "Bermudian Dollar (BMD)", currency: "BMD", symbol: "$", flag: "https://flagcdn.com/bm.svg" },
  { name: "Brunei Dollar (BND)", currency: "BND", symbol: "$", flag: "https://flagcdn.com/bn.svg" },
  { name: "Bolivian Boliviano (BOB)", currency: "BOB", symbol: "Bs.", flag: "https://flagcdn.com/bo.svg" },
  { name: "Brazilian Real (BRL)", currency: "BRL", symbol: "R$", flag: "https://flagcdn.com/br.svg" },
  { name: "Bahamian Dollar (BSD)", currency: "BSD", symbol: "$", flag: "https://flagcdn.com/bs.svg" },
  { name: "Bhutanese Ngultrum (BTN)", currency: "BTN", symbol: "Nu.", flag: "https://flagcdn.com/bt.svg" },
  { name: "Botswana Pula (BWP)", currency: "BWP", symbol: "P", flag: "https://flagcdn.com/bw.svg" },
  { name: "Belarusian Ruble (BYN)", currency: "BYN", symbol: "Br", flag: "https://flagcdn.com/by.svg" },
  { name: "Belize Dollar (BZD)", currency: "BZD", symbol: "$", flag: "https://flagcdn.com/bz.svg" },
  { name: "Canadian Dollar (CAD)", currency: "CAD", symbol: "$", flag: "https://flagcdn.com/ca.svg" },
  { name: "Congolese Franc (CDF)", currency: "CDF", symbol: "FC", flag: "https://flagcdn.com/cd.svg" },
  { name: "Swiss Franc (CHF)", currency: "CHF", symbol: "CHF", flag: "https://flagcdn.com/ch.svg" },
  { name: "Chilean Peso (CLP)", currency: "CLP", symbol: "$", flag: "https://flagcdn.com/cl.svg" },
  { name: "Chinese Yuan (CNY)", currency: "CNY", symbol: "¥", flag: "https://flagcdn.com/cn.svg" },
  { name: "Colombian Peso (COP)", currency: "COP", symbol: "$", flag: "https://flagcdn.com/co.svg" },
  { name: "Costa Rican Colon (CRC)", currency: "CRC", symbol: "₡", flag: "https://flagcdn.com/cr.svg" },
  { name: "Cuban Peso (CUP)", currency: "CUP", symbol: "₱", flag: "https://flagcdn.com/cu.svg" },
  { name: "Cape Verdean Escudo (CVE)", currency: "CVE", symbol: "$", flag: "https://flagcdn.com/cv.svg" },
  { name: "Czech Koruna (CZK)", currency: "CZK", symbol: "Kč", flag: "https://flagcdn.com/cz.svg" },
  { name: "Djiboutian Franc (DJF)", currency: "DJF", symbol: "Fdj", flag: "https://flagcdn.com/dj.svg" },
  { name: "Danish Krone (DKK)", currency: "DKK", symbol: "kr", flag: "https://flagcdn.com/dk.svg" },
  { name: "Dominican Peso (DOP)", currency: "DOP", symbol: "RD$", flag: "https://flagcdn.com/do.svg" },
  { name: "Algerian Dinar (DZD)", currency: "DZD", symbol: "دج", flag: "https://flagcdn.com/dz.svg" },
  { name: "Egyptian Pound (EGP)", currency: "EGP", symbol: "£", flag: "https://flagcdn.com/eg.svg" },
  { name: "Eritrean Nakfa (ERN)", currency: "ERN", symbol: "Nfk", flag: "https://flagcdn.com/er.svg" },
  { name: "Ethiopian Birr (ETB)", currency: "ETB", symbol: "Br", flag: "https://flagcdn.com/et.svg" },
  { name: "Euro (EUR)", currency: "EUR", symbol: "€", flag: "https://flagcdn.com/eu.svg" },
  { name: "Fiji Dollar (FJD)", currency: "FJD", symbol: "$", flag: "https://flagcdn.com/fj.svg" },
  { name: "Falkland Islands Pound (FKP)", currency: "FKP", symbol: "£", flag: "https://flagcdn.com/fk.svg" },
  { name: "Georgian Lari (GEL)", currency: "GEL", symbol: "₾", flag: "https://flagcdn.com/ge.svg" },
  { name: "Ghanaian Cedi (GHS)", currency: "GHS", symbol: "₵", flag: "https://flagcdn.com/gh.svg" },
  { name: "Gibraltar Pound (GIP)", currency: "GIP", symbol: "£", flag: "https://flagcdn.com/gi.svg" },
  { name: "Gambian Dalasi (GMD)", currency: "GMD", symbol: "D", flag: "https://flagcdn.com/gm.svg" },
  { name: "Guinean Franc (GNF)", currency: "GNF", symbol: "FG", flag: "https://flagcdn.com/gn.svg" },
  { name: "Guinean Franc (GNF)", currency: "GNF", symbol: "FG", flag: "https://flagcdn.com/gn.svg" },
  { name: "Guatemalan Quetzal (GTQ)", currency: "GTQ", symbol: "Q", flag: "https://flagcdn.com/gt.svg" },
  { name: "Guyanese Dollar (GYD)", currency: "GYD", symbol: "$", flag: "https://flagcdn.com/gy.svg" },
  { name: "Hong Kong Dollar (HKD)", currency: "HKD", symbol: "$", flag: "https://flagcdn.com/hk.svg" },
  { name: "Honduran Lempira (HNL)", currency: "HNL", symbol: "L", flag: "https://flagcdn.com/hn.svg" },
  { name: "Croatian Kuna (HRK)", currency: "HRK", symbol: "kn", flag: "https://flagcdn.com/hr.svg" },
  { name: "Haitian Gourde (HTG)", currency: "HTG", symbol: "G", flag: "https://flagcdn.com/ht.svg" },
  { name: "Hungarian Forint (HUF)", currency: "HUF", symbol: "Ft", flag: "https://flagcdn.com/hu.svg" },
  { name: "Indonesian Rupiah (IDR)", currency: "IDR", symbol: "Rp", flag: "https://flagcdn.com/id.svg" },
  { name: "Israeli New Shekel (ILS)", currency: "ILS", symbol: "₪", flag: "https://flagcdn.com/il.svg" },
  { name: "Indian Rupee (INR)", currency: "INR", symbol: "₹", flag: "https://flagcdn.com/in.svg" },
  { name: "Iraqi Dinar (IQD)", currency: "IQD", symbol: "ع.د", flag: "https://flagcdn.com/iq.svg" },
  { name: "Iranian Rial (IRR)", currency: "IRR", symbol: "﷼", flag: "https://flagcdn.com/ir.svg" },
  { name: "Icelandic Króna (ISK)", currency: "ISK", symbol: "kr", flag: "https://flagcdn.com/is.svg" },
  { name: "Jamaican Dollar (JMD)", currency: "JMD", symbol: "J$", flag: "https://flagcdn.com/jm.svg" },
  { name: "Jordanian Dinar (JOD)", currency: "JOD", symbol: "د.ا", flag: "https://flagcdn.com/jo.svg" },
  { name: "Japanese Yen (JPY)", currency: "JPY", symbol: "¥", flag: "https://flagcdn.com/jp.svg" },
  { name: "Kenyan Shilling (KES)", currency: "KES", symbol: "KSh", flag: "https://flagcdn.com/ke.svg" },
  { name: "Kyrgyzstani Som (KGS)", currency: "KGS", symbol: "с", flag: "https://flagcdn.com/kg.svg" },
  { name: "Cambodian Riel (KHR)", currency: "KHR", symbol: "៛", flag: "https://flagcdn.com/kh.svg" },
  { name: "Comorian Franc (KMF)", currency: "KMF", symbol: "CF", flag: "https://flagcdn.com/km.svg" },
  { name: "North Korean Won (KPW)", currency: "KPW", symbol: "₩", flag: "https://flagcdn.com/kp.svg" },
  { name: "South Korean Won (KRW)", currency: "KRW", symbol: "₩", flag: "https://flagcdn.com/kr.svg" },
  { name: "Kuwaiti Dinar (KWD)", currency: "KWD", symbol: "د.ك", flag: "https://flagcdn.com/kw.svg" },
  { name: "Cayman Islands Dollar (KYD)", currency: "KYD", symbol: "$", flag: "https://flagcdn.com/ky.svg" },
  { name: "Kazakhstani Tenge (KZT)", currency: "KZT", symbol: "₸", flag: "https://flagcdn.com/kz.svg" },
  { name: "Lao Kip (LAK)", currency: "LAK", symbol: "₭", flag: "https://flagcdn.com/la.svg" },
  { name: "Lebanese Pound (LBP)", currency: "LBP", symbol: "ل.ل", flag: "https://flagcdn.com/lb.svg" },
  { name: "Sri Lankan Rupee (LKR)", currency: "LKR", symbol: "Rs", flag: "https://flagcdn.com/lk.svg" },
  { name: "Liberian Dollar (LRD)", currency: "LRD", symbol: "$", flag: "https://flagcdn.com/lr.svg" },
  { name: "Lesotho Loti (LSL)", currency: "LSL", symbol: "L", flag: "https://flagcdn.com/ls.svg" },
  { name: "Libyan Dinar (LYD)", currency: "LYD", symbol: "ل.د", flag: "https://flagcdn.com/ly.svg" },
  { name: "Moroccan Dirham (MAD)", currency: "MAD", symbol: "د.م.", flag: "https://flagcdn.com/ma.svg" },
  { name: "Moldovan Leu (MDL)", currency: "MDL", symbol: "L", flag: "https://flagcdn.com/md.svg" },
  { name: "Malagasy Ariary (MGA)", currency: "MGA", symbol: "Ar", flag: "https://flagcdn.com/mg.svg" },
  { name: "Macedonian Denar (MKD)", currency: "MKD", symbol: "ден", flag: "https://flagcdn.com/mk.svg" },
  { name: "Myanmar Kyat (MMK)", currency: "MMK", symbol: "K", flag: "https://flagcdn.com/mm.svg" },
  { name: "Mongolian Tögrög (MNT)", currency: "MNT", symbol: "₮", flag: "https://flagcdn.com/mn.svg" },
  { name: "Macanese Pataca (MOP)", currency: "MOP", symbol: "P", flag: "https://flagcdn.com/mo.svg" },
  { name: "Mauritanian Ouguiya (MRU)", currency: "MRU", symbol: "UM", flag: "https://flagcdn.com/mr.svg" },
  { name: "Mauritian Rupee (MUR)", currency: "MUR", symbol: "₨", flag: "https://flagcdn.com/mu.svg" },
  { name: "Maldivian Rufiyaa (MVR)", currency: "MVR", symbol: "Rf", flag: "https://flagcdn.com/mv.svg" },
  { name: "Malawian Kwacha (MWK)", currency: "MWK", symbol: "MK", flag: "https://flagcdn.com/mw.svg" },
  { name: "Mexican Peso (MXN)", currency: "MXN", symbol: "$", flag: "https://flagcdn.com/mx.svg" },
  { name: "Malaysian Ringgit (MYR)", currency: "MYR", symbol: "RM", flag: "https://flagcdn.com/my.svg" },
  { name: "Mozambican Metical (MZN)", currency: "MZN", symbol: "MT", flag: "https://flagcdn.com/mz.svg" },
  { name: "Namibian Dollar (NAD)", currency: "NAD", symbol: "$", flag: "https://flagcdn.com/na.svg" },
  { name: "Nigerien Franc (XOF)", currency: "XOF", symbol: "CFA", flag: "https://flagcdn.com/ne.svg" },
  { name: "Nicaraguan Córdoba (NIO)", currency: "NIO", symbol: "C$", flag: "https://flagcdn.com/ni.svg" },
  { name: "Norwegian Krone (NOK)", currency: "NOK", symbol: "kr", flag: "https://flagcdn.com/no.svg" },
  { name: "Nepalese Rupee (NPR)", currency: "NPR", symbol: "Rs", flag: "https://flagcdn.com/np.svg" },
  { name: "New Zealand Dollar (NZD)", currency: "NZD", symbol: "$", flag: "https://flagcdn.com/nz.svg" },
  { name: "Omani Rial (OMR)", currency: "OMR", symbol: "ر.ع.", flag: "https://flagcdn.com/om.svg" },
  { name: "Panamanian Balboa (PAB)", currency: "PAB", symbol: "B/.", flag: "https://flagcdn.com/pa.svg" },
  { name: "Peruvian Sol (PEN)", currency: "PEN", symbol: "S/", flag: "https://flagcdn.com/pe.svg" },
  { name: "Papua New Guinean Kina (PGK)", currency: "PGK", symbol: "K", flag: "https://flagcdn.com/pg.svg" },
  { name: "Philippine Peso (PHP)", currency: "PHP", symbol: "₱", flag: "https://flagcdn.com/ph.svg" },
  { name: "Pakistani Rupee (PKR)", currency: "PKR", symbol: "₨", flag: "https://flagcdn.com/pk.svg" },
  { name: "Polish Złoty (PLN)", currency: "PLN", symbol: "zł", flag: "https://flagcdn.com/pl.svg" },
  { name: "Paraguayan Guaraní (PYG)", currency: "PYG", symbol: "₲", flag: "https://flagcdn.com/py.svg" },
  { name: "Qatari Riyal (QAR)", currency: "QAR", symbol: "ر.ق", flag: "https://flagcdn.com/qa.svg" },
  { name: "Romanian Leu (RON)", currency: "RON", symbol: "lei", flag: "https://flagcdn.com/ro.svg" },
  { name: "Serbian Dinar (RSD)", currency: "RSD", symbol: "дин", flag: "https://flagcdn.com/rs.svg" },
  { name: "Russian Ruble (RUB)", currency: "RUB", symbol: "₽", flag: "https://flagcdn.com/ru.svg" },
  { name: "Rwandan Franc (RWF)", currency: "RWF", symbol: "FRw", flag: "https://flagcdn.com/rw.svg" },
  { name: "Saudi Riyal (SAR)", currency: "SAR", symbol: "ر.س", flag: "https://flagcdn.com/sa.svg" },
  { name: "Solomon Islands Dollar (SBD)", currency: "SBD", symbol: "$", flag: "https://flagcdn.com/sb.svg" },
  { name: "Seychellois Rupee (SCR)", currency: "SCR", symbol: "₨", flag: "https://flagcdn.com/sc.svg" },
  { name: "Sudanese Pound (SDG)", currency: "SDG", symbol: "ج.س.", flag: "https://flagcdn.com/sd.svg" },
  { name: "Swedish Krona (SEK)", currency: "SEK", symbol: "kr", flag: "https://flagcdn.com/se.svg" },
  { name: "Singapore Dollar (SGD)", currency: "SGD", symbol: "$", flag: "https://flagcdn.com/sg.svg" },
  { name: "Saint Helena Pound (SHP)", currency: "SHP", symbol: "£", flag: "https://flagcdn.com/sh.svg" },
  { name: "Sierra Leonean Leone (SLE)", currency: "SLE", symbol: "Le", flag: "https://flagcdn.com/sl.svg" },
  { name: "Somali Shilling (SOS)", currency: "SOS", symbol: "Sh", flag: "https://flagcdn.com/so.svg" },
  { name: "Surinamese Dollar (SRD)", currency: "SRD", symbol: "$", flag: "https://flagcdn.com/sr.svg" },
  { name: "South Sudanese Pound (SSP)", currency: "SSP", symbol: "£", flag: "https://flagcdn.com/ss.svg" },
  { name: "São Tomé and Príncipe Dobra (STN)", currency: "STN", symbol: "Db", flag: "https://flagcdn.com/st.svg" },
  { name: "Syrian Pound (SYP)", currency: "SYP", symbol: "£", flag: "https://flagcdn.com/sy.svg" },
  { name: "Swazi Lilangeni (SZL)", currency: "SZL", symbol: "L", flag: "https://flagcdn.com/sz.svg" },
  { name: "Thai Baht (THB)", currency: "THB", symbol: "฿", flag: "https://flagcdn.com/th.svg" },
  { name: "Tajikistani Somoni (TJS)", currency: "TJS", symbol: "ЅМ", flag: "https://flagcdn.com/tj.svg" },
  { name: "Turkmenistani Manat (TMT)", currency: "TMT", symbol: "m", flag: "https://flagcdn.com/tm.svg" },
  { name: "Tunisian Dinar (TND)", currency: "TND", symbol: "د.ت", flag: "https://flagcdn.com/tn.svg" },
  { name: "Tongan Paʻanga (TOP)", currency: "TOP", symbol: "T$", flag: "https://flagcdn.com/to.svg" },
  { name: "Turkish Lira (TRY)", currency: "TRY", symbol: "₺", flag: "https://flagcdn.com/tr.svg" },
  { name: "Trinidad and Tobago Dollar (TTD)", currency: "TTD", symbol: "$", flag: "https://flagcdn.com/tt.svg" },
  { name: "New Taiwan Dollar (TWD)", currency: "TWD", symbol: "NT$", flag: "https://flagcdn.com/tw.svg" },
  { name: "Tanzanian Shilling (TZS)", currency: "TZS", symbol: "Sh", flag: "https://flagcdn.com/tz.svg" },
  { name: "Ukrainian Hryvnia (UAH)", currency: "UAH", symbol: "₴", flag: "https://flagcdn.com/ua.svg" },
  { name: "Ugandan Shilling (UGX)", currency: "UGX", symbol: "USh", flag: "https://flagcdn.com/ug.svg" },
  { name: "Uruguayan Peso (UYU)", currency: "UYU", symbol: "$U", flag: "https://flagcdn.com/uy.svg" },
  { name: "Uzbekistani Som (UZS)", currency: "UZS", symbol: "лв", flag: "https://flagcdn.com/uz.svg" },
  { name: "Venezuelan Bolívar (VES)", currency: "VES", symbol: "Bs", flag: "https://flagcdn.com/ve.svg" },
  { name: "Vietnamese Đồng (VND)", currency: "VND", symbol: "₫", flag: "https://flagcdn.com/vn.svg" },
  { name: "Vanuatu Vatu (VUV)", currency: "VUV", symbol: "Vt", flag: "https://flagcdn.com/vu.svg" },
  { name: "Samoan Tālā (WST)", currency: "WST", symbol: "T", flag: "https://flagcdn.com/ws.svg" },
  { name: "CFA Franc BEAC (XAF)", currency: "XAF", symbol: "FCFA", flag: "https://flagcdn.com/cm.svg" },
  { name: "CFA Franc BCEAO (XOF)", currency: "XOF", symbol: "CFA", flag: "https://flagcdn.com/sn.svg" },
  { name: "CFP Franc (XPF)", currency: "XPF", symbol: "₣", flag: "https://flagcdn.com/pf.svg" },
  { name: "Yemeni Rial (YER)", currency: "YER", symbol: "﷼", flag: "https://flagcdn.com/ye.svg" },
  { name: "South African Rand (ZAR)", currency: "ZAR", symbol: "R", flag: "https://flagcdn.com/za.svg" },
  { name: "Zambian Kwacha (ZMW)", currency: "ZMW", symbol: "ZK", flag: "https://flagcdn.com/zm.svg" },
  { name: "Zimbabwean Dollar (ZWL)", currency: "ZWL", symbol: "$", flag: "https://flagcdn.com/zw.svg" },
];

